### ISSUE TITLE
переработать концепт функции Chain::form_yield_map

### ISSUE THREAD

**Issue by dryuri92** [ivanbukhtiyarov/nuclideParser#6]
не ну вот тут реальное "читерство" 
`out.insert({"0.0253", en_1});
        out.insert({"500000.0", en_2});
        out.insert({"2000000.0", en_3});
        out.insert({"14000000.0", en_4});
`
при этом вот здесь его нет! 
`out.insert({"(n,2n)", n_2n});
        out.insert({"(n,3n)", n_3n});
        out.insert({"(n,gamma)", n_gamma});
        out.insert({"(n,a)", n_a});
        out.insert({"(n,p)", n_p});`
дело в том, что в первом случае я понятия предварительного не имею для каких энергий у меня есть данные, в случае же с реакциями дело другое - там других для нашей задачи и быть не может, поэтому такое допускается.
Но даже делая скидку на то что у тебя не было всей информации, текст кода даже как-то поприятнее у тебя прописан в `form_reaction();`. Так что да, необходимо делать двойной прогон по файлу, причем можно реализовать ф-ю, которая в контейнер после прогона будет класть эти все значения энергий  в double формате или присваивать аттрибуту класса в виде контейнера, т.к. они потом будут использоваться в вычисоениях.

**Comment by ivanbukhtiyarov** [comment]
1) Изменил структуру выходных данных с std::map<std::string, std::vector<std::vector<double>>> на std::map<double, std::vector<std::vector<double>>>
для того чтобы к выходным данным соответствующим нужной энергии можно было обращаться в произвольном формате значения этой самой энергии.
2) переработал логику функции формирования данных, как вы просили
